### PR TITLE
Remove `cabal2nix` codegen

### PR DESCRIPTION
**Pull request by evanrelf**
Use `pkgs.haskell.lib.packageSourceOverrides` to simplify pinning
Haskell package versions.

### CODE REVIEW

**Review by ixmatus — APPROVED** [review]
Much nicer, thanks.

**Comment by evanrelf** [comment]
Let's wait until we can run this through CI and have it build successfully before merging.

**Comment by riz0id** [comment]
Sweet, thank you

**Review by riz0id — APPROVED** [review]

**Comment by evanrelf** [comment]
Closing in favor of updating Nixpkgs in https://github.com/awakesecurity/spectacle/pull/3, obviating the need to pin Haskell packages

**Pull request closed without merging**
