### PR TITLE
More Nix simplifications

### PR DESCRIPTION
**Pull request by evanrelf**
Saw places where the Nix infrastructure could be even simpler.

Commits are atomic and the commit messages are descriptive; I recommend reviewing them individually.

### CODE REVIEW

**Comment by riz0id** [comment]
I'm totally in favor of fourmolu options being defined in a yaml file rather than nix.

**Review by riz0id — APPROVED** [review]

**Comment by evanrelf** [comment]
@ixmatus We're using `fourmolu` in `end-to-end` with this `fourmolu.yaml` setup without any issues, and it worked as intended in this PR, so I don't think that's an issue.

If there are issues in the future, I suggest defining the options in `scripts/fourmolu` directly, similar to how we already do with language extensions, instead of threading them through a bunch of Nix files.

**Comment by ixmatus** [comment]
@evanrelf I never said it was an issue :)

I prefer explicit arguments over implicit config files, that was the primary reason for my doing it that way originally. There is nothing broken about your approach in this PR (I would have said something if I thought that was the case) and your proposed change here is fine and I agree with it. I explained the rationale not to argue or debate your approach but to explain why I did it the way I had, since there was a reason, even if it was slightly rushed :)

**Comment by evanrelf** [comment]
@ixmatus Ah okay, I misinterpreted you 🙂

**Pull request merged**
